# Generated by Django 2.0 on 2018-05-01 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationmodel',
            name='eventRelated',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='event.EventModel'),
        ),
        migrations.AddField(
            model_name='notificationmodel',
            name='photoEventRelated',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='event.PhotoEventModel'),
        ),
        migrations.AddField(
            model_name='notificationmodel',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='notifications', to='account.ProfileModel'),
        ),
        migrations.AddField(
            model_name='notificationmodel',
            name='profileRelated',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='account.ProfileModel'),
        ),
    ]
