# Generated by Django 2.0 on 2018-05-11 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20180501_2242'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notificationmodel',
            old_name='date_created',
            new_name='dateCreated',
        ),
        migrations.RenameField(
            model_name='notificationmodel',
            old_name='date_removed',
            new_name='dateRemoved',
        ),
    ]
