# Generated by Django 2.0 on 2018-05-27 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20180511_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationmodel',
            name='profileRelated',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account.ProfileModel'),
        ),
    ]
