# Generated by Django 2.0 on 2017-12-31 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.IntegerField(choices=[(1, 'Birthday'), (2, 'Wedding'), (3, 'Christmass'), (4, 'New year'), (5, 'Other')], default=1),
        ),
    ]
