# Generated by Django 2.0 on 2018-01-09 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20180109_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photoevent',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='events.Event'),
        ),
    ]
