# Generated by Django 2.0 on 2018-01-09 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20180109_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='involvement',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='events.Event'),
        ),
    ]
