# Generated by Django 2.0 on 2018-01-02 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20171231_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='photoevent',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
