# Generated by Django 2.0 on 2018-01-03 19:29

from django.db import migrations, models
import events.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_photoevent_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='photo_event',
            field=models.ImageField(blank=True, null=True, upload_to=events.models.file_path_event_photo),
        ),
    ]
