# Generated by Django 2.0 on 2018-01-07 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='accounts.Profile')),
                ('following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to='accounts.Profile')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='profiles_following',
            field=models.ManyToManyField(through='accounts.Follow', to='accounts.Profile'),
        ),
    ]
