<<<<<<< HEAD:events/migrations/0001_initial.py
# Generated by Django 2.0 on 2018-01-07 21:33
=======
# Generated by Django 2.0 on 2018-05-01 20:42
>>>>>>> 9f2c1ce7f3118310e93bcf24a89c451064f86846:event/migrations/0001_initial.py

from django.db import migrations, models
import django.db.models.deletion
import event.models.event_model
import event.models.photo_event_model


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD:events/migrations/0001_initial.py
        ('accounts', '0001_initial'),
=======
        ('account', '0001_initial'),
>>>>>>> 9f2c1ce7f3118310e93bcf24a89c451064f86846:event/migrations/0001_initial.py
    ]

    operations = [
        migrations.CreateModel(
            name='EventModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=42)),
                ('description', models.TextField(null=True)),
                ('date_start', models.DateTimeField()),
                ('date_end', models.DateTimeField()),
                ('theme', models.IntegerField(choices=[(1, 'Birthday'), (2, 'Wedding'), (3, 'Christmass'), (4, 'New year'), (5, 'Other')], default=5)),
<<<<<<< HEAD:events/migrations/0001_initial.py
                ('photo_event', models.ImageField(blank=True, null=True, upload_to=events.models.file_path_event_photo)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator', to='accounts.Profile')),
=======
                ('photo_event', models.ImageField(blank=True, null=True, upload_to=event.models.event_model.file_path_event_photo)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator', to='account.ProfileModel')),
>>>>>>> 9f2c1ce7f3118310e93bcf24a89c451064f86846:event/migrations/0001_initial.py
            ],
        ),
        migrations.CreateModel(
            name='InvolvementModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='participants', to='event.EventModel')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='involves', to='account.ProfileModel')),
            ],
        ),
        migrations.CreateModel(
            name='PhotoEventModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD:events/migrations/0001_initial.py
                ('photo', models.ImageField(blank=True, null=True, upload_to=events.models.file_path)),
                ('title', models.CharField(default='', max_length=100)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event')),
                ('owner', models.ForeignKey(default=13, on_delete=django.db.models.deletion.CASCADE, related_name='own_photo', to='accounts.Profile')),
=======
                ('photo', models.ImageField(blank=True, null=True, upload_to=event.models.photo_event_model.file_path)),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='event.EventModel')),
                ('owner', models.ForeignKey(default=13, on_delete=django.db.models.deletion.CASCADE, related_name='own_photos', to='account.ProfileModel')),
>>>>>>> 9f2c1ce7f3118310e93bcf24a89c451064f86846:event/migrations/0001_initial.py
            ],
        ),
        migrations.AddField(
            model_name='eventmodel',
            name='entries',
            field=models.ManyToManyField(through='event.InvolvementModel', to='account.ProfileModel'),
        ),
        migrations.AlterUniqueTogether(
            name='involvementmodel',
            unique_together={('event', 'profile')},
        ),
    ]
