# Generated by Django 2.0 on 2018-05-01 20:42

from django.db import migrations, models
import django.db.models.deletion
import event.models.event_model
import event.models.photo_event_model


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=42)),
                ('description', models.TextField(null=True)),
                ('date_start', models.DateTimeField()),
                ('date_end', models.DateTimeField()),
                ('theme', models.IntegerField(choices=[(1, 'Birthday'), (2, 'Wedding'), (3, 'Christmass'), (4, 'New year'), (5, 'Other')], default=5)),
                ('photo_event', models.ImageField(blank=True, null=True, upload_to=event.models.event_model.file_path_event_photo)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator', to='account.ProfileModel')),
            ],
        ),
        migrations.CreateModel(
            name='InvolvementModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='participants', to='event.EventModel')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='involves', to='account.ProfileModel')),
            ],
        ),
        migrations.CreateModel(
            name='PhotoEventModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to=event.models.photo_event_model.file_path)),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='event.EventModel')),
                ('owner', models.ForeignKey(default=13, on_delete=django.db.models.deletion.CASCADE, related_name='own_photos', to='account.ProfileModel')),
            ],
        ),
        migrations.AddField(
            model_name='eventmodel',
            name='entries',
            field=models.ManyToManyField(through='event.InvolvementModel', to='account.ProfileModel'),
        ),
        migrations.AlterUniqueTogether(
            name='involvementmodel',
            unique_together={('event', 'profile')},
        ),
    ]
